### ISSUE TITLE
People - Figure Out How to Handle Alumni

### ISSUE THREAD

**Issue by fcjou** [uwdub/web-dub#211]
In order to figure out how best to structure and organize the 'people' files, we first need to determine how we want to handle alumni.

Suppose this special case person exists:
- Currently a professor in multiple departments
- Previously a PhD student at UW
- Previously a Master's student at UW

Some questions arise:
- Do we want to keep alumni files in our system? (currently we do have an alumni folder)
- Do we want to display alumni in their own section on our website? Is this important?
- If someone has current and alumni roles (e.g. above), do we want to retain and/or display the alumni information? Together? Separately?
- How will we maintain alumni status/info (people graduate, drop out)? Keep track of their graduation date? Manually update an alumni status flag and move them from one folder to another? Will we eventually want more organization beyond 'alumni' and 'current' such as graduation year?

If we don't care about displaying alumni info at all, that simplifies how we can think about organizing people by A LOT. Then we can follow something like what came out of the discussions for #63 :

```
role:
  - faculty
position:
  - title: Assistant Professor
    unit: Information School

role:
  - doctoral-student
position:
  - unit: Information School

role:
  - masters-student
position:
  - unit: Master of Science in Information Management
```

However, if a person has multiple roles (say... faculty AND doctoral-student-alumni) then there would be no way to tell which unit is associated with which role.

Currently my solution for designing around the 'special case person' is this:

```
role:
  - faculty:
    is-alumni: false
    position:
      - title: Associate Professor
        unit: Information School
      - title: Assistant Professor
        unit: Division of Design
  - doctoral-student:
    is-alumni: true
    position:
       - unit: Information School
  - masters-student:
    is-alumni: true
    position:
      - unit: Master of Design
```
Another variation is having alumni roles (e.g. faculty-alumni, doctoral-alumni) instead of having an is-alumni flag, or to have a field for graduation year for students. Either way, we need to have alumni information in the file itself, otherwise we'd have to resort to having multiple files for that 'special case' person, which is something undesirable.

Thoughts? Am I overthinking this?
