### ISSUE TITLE
Publication Files Should Be Named by ID

### ISSUE THREAD

**Issue by jayfo** [uwdub/web-dub#28]
Instead of this:

``` yml
id_conferencepaper_pervasive2010_welbourne_evan:
  authors:
  - id_author_welbourne_evan
  - id_author_balazinska_magdalena
  - id_author_borriello_gaetano
  - id_author_fogarty_james
  conference: id_conference_pervasive2010
  localpdf: pervasive2010.pdf
  localthumb: pervasive2010.png
  officialurl: http://dx.doi.org/10.1007/978-3-642-12654-3_4
  pages: 57-75
  title: Specification and Verification of Complex Location Events with Panoramic
```

We should have this:

``` yml
id_conferencepaper_pervasive2010_welbourne_evan:
  authors:
  - id_author_welbourne_evan
  - id_author_balazinska_magdalena
  - id_author_borriello_gaetano
  - id_author_fogarty_james
  conference: id_conference_pervasive2010
  localpdf: pervasive2010_welbourne_evan.pdf
  localthumb: pervasive2010_welbourne_evan.png
  officialurl: http://dx.doi.org/10.1007/978-3-642-12654-3_4
  pages: 57-75
  title: Specification and Verification of Complex Location Events with Panoramic
```

Note the different `localpdf` and `localthumb`.

Similarly for other publication fields and types.
